"""empty message

Revision ID: 3184c19329ae
Revises: 638955743d09
Create Date: 2018-02-11 14:17:11.997937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3184c19329ae'
down_revision = '638955743d09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_module_name', table_name='module')
    op.create_index(op.f('ix_module_name'), 'module', ['name'], unique=False)
    op.add_column('user', sa.Column('firstname', sa.String(length=64), nullable=True))
    op.add_column('user', sa.Column('lastname', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'lastname')
    op.drop_column('user', 'firstname')
    op.drop_index(op.f('ix_module_name'), table_name='module')
    op.create_index('ix_module_name', 'module', ['name'], unique=1)
    # ### end Alembic commands ###
