"""empty message

Revision ID: 89bc22376699
Revises: 3184c19329ae
Create Date: 2018-02-11 18:43:38.398948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89bc22376699'
down_revision = '3184c19329ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('module_institutions',
    sa.Column('module_id', sa.Integer(), nullable=True),
    sa.Column('institution_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['institution_id'], ['institution.id'], ),
    sa.ForeignKeyConstraint(['module_id'], ['module.id'], )
    )
    op.drop_table('institution_modules')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('institution_modules',
    sa.Column('institution_id', sa.INTEGER(), nullable=True),
    sa.Column('module_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['institution_id'], ['institution.id'], ),
    sa.ForeignKeyConstraint(['module_id'], ['module.id'], )
    )
    op.drop_table('module_institutions')
    # ### end Alembic commands ###
