"""empty message

Revision ID: acbd3054d02d
Revises: 1f7148c741ab
Create Date: 2018-02-24 15:41:09.790460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acbd3054d02d'
down_revision = '1f7148c741ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course', 'updated_up')
    op.add_column('course', sa.Column('updated_at', sa.DateTime(), nullable=True)) 
    op.drop_column('institution', 'updated_up')
    op.add_column('institution', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.drop_column('module', 'updated_up')
    op.add_column('module', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.drop_column('tag', 'updated_up')
    op.add_column('tag', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.drop_column('user', 'updated_up')
    op.add_column('user', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('updated_up', sa.DATETIME(), nullable=True))
    op.drop_column('user', 'updated_at')
    op.add_column('tag', sa.Column('updated_up', sa.DATETIME(), nullable=True))
    op.drop_column('tag', 'updated_at')
    op.add_column('module', sa.Column('updated_up', sa.DATETIME(), nullable=True))
    op.drop_column('module', 'updated_at')
    op.add_column('institution', sa.Column('updated_up', sa.DATETIME(), nullable=True))
    op.drop_column('institution', 'updated_at')
    op.add_column('course', sa.Column('updated_up', sa.DATETIME(), nullable=True))
    # ### end Alembic commands ###
