"""empty message

Revision ID: fe3f6e8889d0
Revises: 89bc22376699
Create Date: 2018-02-17 19:00:11.229228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe3f6e8889d0'
down_revision = '89bc22376699'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('module', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('module', 'description')
    # ### end Alembic commands ###
